# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 540)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 631, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.config = QtWidgets.QWidget()
        self.config.setObjectName("config")
        self.label = QtWidgets.QLabel(self.config)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.mode_btn = QtWidgets.QPushButton(self.config)
        self.mode_btn.setGeometry(QtCore.QRect(210, 110, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mode_btn.setFont(font)
        self.mode_btn.setObjectName("mode_btn")
        self.syringe_btn = QtWidgets.QPushButton(self.config)
        self.syringe_btn.setGeometry(QtCore.QRect(210, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.syringe_btn.setFont(font)
        self.syringe_btn.setObjectName("syringe_btn")
        self.rate_btn = QtWidgets.QPushButton(self.config)
        self.rate_btn.setEnabled(True)
        self.rate_btn.setGeometry(QtCore.QRect(210, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rate_btn.setFont(font)
        self.rate_btn.setObjectName("rate_btn")
        self.target_btn = QtWidgets.QPushButton(self.config)
        self.target_btn.setGeometry(QtCore.QRect(210, 260, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.target_btn.setFont(font)
        self.target_btn.setObjectName("target_btn")
        self.empty_btn = QtWidgets.QPushButton(self.config)
        self.empty_btn.setGeometry(QtCore.QRect(180, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.empty_btn.setFont(font)
        self.empty_btn.setObjectName("empty_btn")
        self.fill_btn = QtWidgets.QPushButton(self.config)
        self.fill_btn.setGeometry(QtCore.QRect(330, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fill_btn.setFont(font)
        self.fill_btn.setObjectName("fill_btn")
        self.run_btn = QtWidgets.QPushButton(self.config)
        self.run_btn.setGeometry(QtCore.QRect(270, 380, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.run_btn.setFont(font)
        self.run_btn.setObjectName("run_btn")
        self.checkBox = QtWidgets.QCheckBox(self.config)
        self.checkBox.setGeometry(QtCore.QRect(470, 180, 87, 20))
        self.checkBox.setObjectName("checkBox")
        self.mode_table = QtWidgets.QTableWidget(self.config)
        self.mode_table.setGeometry(QtCore.QRect(340, 110, 101, 31))
        self.mode_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mode_table.setObjectName("mode_table")
        self.mode_table.setColumnCount(1)
        self.mode_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.mode_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mode_table.setHorizontalHeaderItem(0, item)
        self.mode_table.horizontalHeader().setVisible(False)
        self.mode_table.horizontalHeader().setHighlightSections(False)
        self.mode_table.verticalHeader().setVisible(False)
        self.syringe_table = QtWidgets.QTableWidget(self.config)
        self.syringe_table.setGeometry(QtCore.QRect(340, 160, 101, 31))
        self.syringe_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.syringe_table.setObjectName("syringe_table")
        self.syringe_table.setColumnCount(1)
        self.syringe_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.syringe_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.syringe_table.setHorizontalHeaderItem(0, item)
        self.syringe_table.horizontalHeader().setVisible(False)
        self.syringe_table.horizontalHeader().setHighlightSections(False)
        self.syringe_table.verticalHeader().setVisible(False)
        self.rate_table = QtWidgets.QTableWidget(self.config)
        self.rate_table.setGeometry(QtCore.QRect(340, 210, 101, 31))
        self.rate_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.rate_table.setObjectName("rate_table")
        self.rate_table.setColumnCount(1)
        self.rate_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.rate_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rate_table.setHorizontalHeaderItem(0, item)
        self.rate_table.horizontalHeader().setVisible(False)
        self.rate_table.horizontalHeader().setHighlightSections(False)
        self.rate_table.verticalHeader().setVisible(False)
        self.target_table_vol = QtWidgets.QTableWidget(self.config)
        self.target_table_vol.setGeometry(QtCore.QRect(340, 260, 101, 31))
        self.target_table_vol.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.target_table_vol.setObjectName("target_table_vol")
        self.target_table_vol.setColumnCount(1)
        self.target_table_vol.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.target_table_vol.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.target_table_vol.setHorizontalHeaderItem(0, item)
        self.target_table_vol.horizontalHeader().setVisible(False)
        self.target_table_vol.horizontalHeader().setHighlightSections(False)
        self.target_table_vol.verticalHeader().setVisible(False)
        self.target_table_time = QtWidgets.QTableWidget(self.config)
        self.target_table_time.setGeometry(QtCore.QRect(480, 260, 101, 31))
        self.target_table_time.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.target_table_time.setObjectName("target_table_time")
        self.target_table_time.setColumnCount(1)
        self.target_table_time.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.target_table_time.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.target_table_time.setHorizontalHeaderItem(0, item)
        self.target_table_time.horizontalHeader().setVisible(False)
        self.target_table_time.horizontalHeader().setHighlightSections(False)
        self.target_table_time.verticalHeader().setVisible(False)
        self.label_21 = QtWidgets.QLabel(self.config)
        self.label_21.setGeometry(QtCore.QRect(430, 265, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.stackedWidget.addWidget(self.config)
        self.mode = QtWidgets.QWidget()
        self.mode.setObjectName("mode")
        self.label_2 = QtWidgets.QLabel(self.mode)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 211, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.mode)
        self.comboBox.setGeometry(QtCore.QRect(260, 210, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.done1_btn = QtWidgets.QPushButton(self.mode)
        self.done1_btn.setGeometry(QtCore.QRect(270, 340, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.done1_btn.setFont(font)
        self.done1_btn.setObjectName("done1_btn")
        self.stackedWidget.addWidget(self.mode)
        self.syringe = QtWidgets.QWidget()
        self.syringe.setObjectName("syringe")
        self.label_3 = QtWidgets.QLabel(self.syringe)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.syringe)
        self.comboBox_2.setGeometry(QtCore.QRect(200, 140, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.done2_btn = QtWidgets.QPushButton(self.syringe)
        self.done2_btn.setGeometry(QtCore.QRect(270, 340, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.done2_btn.setFont(font)
        self.done2_btn.setObjectName("done2_btn")
        self.label_7 = QtWidgets.QLabel(self.syringe)
        self.label_7.setGeometry(QtCore.QRect(160, 190, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.syringe)
        self.label_8.setGeometry(QtCore.QRect(150, 230, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.syringe)
        self.doubleSpinBox.setGeometry(QtCore.QRect(370, 260, 68, 24))
        self.doubleSpinBox.setMinimum(1.0)
        self.doubleSpinBox.setMaximum(20.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_17 = QtWidgets.QLabel(self.syringe)
        self.label_17.setGeometry(QtCore.QRect(150, 260, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.spinBox_4 = QtWidgets.QSpinBox(self.syringe)
        self.spinBox_4.setGeometry(QtCore.QRect(390, 230, 48, 24))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(20)
        self.spinBox_4.setObjectName("spinBox_4")
        self.stackedWidget.addWidget(self.syringe)
        self.rates = QtWidgets.QWidget()
        self.rates.setObjectName("rates")
        self.label_4 = QtWidgets.QLabel(self.rates)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.rates)
        self.comboBox_3.setGeometry(QtCore.QRect(250, 90, 81, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_9 = QtWidgets.QLabel(self.rates)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.rates)
        self.label_10.setGeometry(QtCore.QRect(30, 130, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.rates)
        self.label_11.setGeometry(QtCore.QRect(30, 180, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.maxrate_table = QtWidgets.QTableWidget(self.rates)
        self.maxrate_table.setGeometry(QtCore.QRect(220, 130, 101, 31))
        self.maxrate_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.maxrate_table.setObjectName("maxrate_table")
        self.maxrate_table.setColumnCount(1)
        self.maxrate_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.maxrate_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.maxrate_table.setHorizontalHeaderItem(0, item)
        self.maxrate_table.horizontalHeader().setVisible(False)
        self.maxrate_table.horizontalHeader().setHighlightSections(False)
        self.maxrate_table.verticalHeader().setVisible(False)
        self.label_12 = QtWidgets.QLabel(self.rates)
        self.label_12.setGeometry(QtCore.QRect(20, 280, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.done3_btn = QtWidgets.QPushButton(self.rates)
        self.done3_btn.setGeometry(QtCore.QRect(270, 340, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.done3_btn.setFont(font)
        self.done3_btn.setObjectName("done3_btn")
        self.minrate_table = QtWidgets.QTableWidget(self.rates)
        self.minrate_table.setGeometry(QtCore.QRect(220, 180, 101, 31))
        self.minrate_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.minrate_table.setObjectName("minrate_table")
        self.minrate_table.setColumnCount(1)
        self.minrate_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.minrate_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.minrate_table.setHorizontalHeaderItem(0, item)
        self.minrate_table.horizontalHeader().setVisible(False)
        self.minrate_table.horizontalHeader().setHighlightSections(False)
        self.minrate_table.verticalHeader().setVisible(False)
        self.stepres_table = QtWidgets.QTableWidget(self.rates)
        self.stepres_table.setGeometry(QtCore.QRect(220, 230, 101, 31))
        self.stepres_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.stepres_table.setObjectName("stepres_table")
        self.stepres_table.setColumnCount(1)
        self.stepres_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.stepres_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stepres_table.setHorizontalHeaderItem(0, item)
        self.stepres_table.horizontalHeader().setVisible(False)
        self.stepres_table.horizontalHeader().setHighlightSections(False)
        self.stepres_table.verticalHeader().setVisible(False)
        self.label_20 = QtWidgets.QLabel(self.rates)
        self.label_20.setGeometry(QtCore.QRect(30, 220, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.units_table = QtWidgets.QTableWidget(self.rates)
        self.units_table.setGeometry(QtCore.QRect(320, 280, 101, 31))
        self.units_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.units_table.setObjectName("units_table")
        self.units_table.setColumnCount(1)
        self.units_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.units_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.units_table.setHorizontalHeaderItem(0, item)
        self.units_table.horizontalHeader().setVisible(False)
        self.units_table.horizontalHeader().setHighlightSections(False)
        self.units_table.verticalHeader().setVisible(False)
        self.rate_box = QtWidgets.QDoubleSpinBox(self.rates)
        self.rate_box.setGeometry(QtCore.QRect(220, 280, 68, 24))
        self.rate_box.setObjectName("rate_box")
        self.stackedWidget.addWidget(self.rates)
        self.target = QtWidgets.QWidget()
        self.target.setObjectName("target")
        self.label_5 = QtWidgets.QLabel(self.target)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.radioButton = QtWidgets.QRadioButton(self.target)
        self.radioButton.setGeometry(QtCore.QRect(50, 90, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.target)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 130, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.target)
        self.spinBox_2.setGeometry(QtCore.QRect(177, 90, 51, 21))
        self.spinBox_2.setMaximum(5000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.target)
        self.spinBox_3.setGeometry(QtCore.QRect(177, 130, 51, 21))
        self.spinBox_3.setMaximum(5000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_13 = QtWidgets.QLabel(self.target)
        self.label_13.setGeometry(QtCore.QRect(240, 130, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.target)
        self.label_14.setGeometry(QtCore.QRect(240, 90, 60, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.target)
        self.label_15.setGeometry(QtCore.QRect(50, 190, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.target)
        self.label_16.setGeometry(QtCore.QRect(50, 240, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.max_vol_table = QtWidgets.QTableWidget(self.target)
        self.max_vol_table.setGeometry(QtCore.QRect(180, 180, 101, 31))
        self.max_vol_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.max_vol_table.setObjectName("max_vol_table")
        self.max_vol_table.setColumnCount(1)
        self.max_vol_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.max_vol_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.max_vol_table.setHorizontalHeaderItem(0, item)
        self.max_vol_table.horizontalHeader().setVisible(False)
        self.max_vol_table.horizontalHeader().setHighlightSections(False)
        self.max_vol_table.verticalHeader().setVisible(False)
        self.max_vol_table.verticalHeader().setHighlightSections(False)
        self.max_time_table = QtWidgets.QTableWidget(self.target)
        self.max_time_table.setGeometry(QtCore.QRect(180, 240, 101, 31))
        self.max_time_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.max_time_table.setObjectName("max_time_table")
        self.max_time_table.setColumnCount(1)
        self.max_time_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.max_time_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.max_time_table.setHorizontalHeaderItem(0, item)
        self.max_time_table.horizontalHeader().setVisible(False)
        self.max_time_table.horizontalHeader().setHighlightSections(False)
        self.max_time_table.verticalHeader().setVisible(False)
        self.max_time_table.verticalHeader().setHighlightSections(False)
        self.done4_btn = QtWidgets.QPushButton(self.target)
        self.done4_btn.setGeometry(QtCore.QRect(270, 340, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.done4_btn.setFont(font)
        self.done4_btn.setObjectName("done4_btn")
        self.stackedWidget.addWidget(self.target)
        self.visuals = QtWidgets.QWidget()
        self.visuals.setObjectName("visuals")
        self.label_6 = QtWidgets.QLabel(self.visuals)
        self.label_6.setGeometry(QtCore.QRect(80, 20, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.stop_btn = QtWidgets.QPushButton(self.visuals)
        self.stop_btn.setGeometry(QtCore.QRect(260, 340, 113, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.display_rate_table = QtWidgets.QTableWidget(self.visuals)
        self.display_rate_table.setGeometry(QtCore.QRect(270, 150, 101, 31))
        self.display_rate_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.display_rate_table.setObjectName("display_rate_table")
        self.display_rate_table.setColumnCount(1)
        self.display_rate_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.display_rate_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_rate_table.setHorizontalHeaderItem(0, item)
        self.display_rate_table.horizontalHeader().setVisible(False)
        self.display_rate_table.horizontalHeader().setHighlightSections(False)
        self.display_rate_table.verticalHeader().setVisible(False)
        self.display_rate_table.verticalHeader().setHighlightSections(False)
        self.display_time_table = QtWidgets.QTableWidget(self.visuals)
        self.display_time_table.setGeometry(QtCore.QRect(270, 220, 101, 31))
        self.display_time_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.display_time_table.setObjectName("display_time_table")
        self.display_time_table.setColumnCount(1)
        self.display_time_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.display_time_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_time_table.setHorizontalHeaderItem(0, item)
        self.display_time_table.horizontalHeader().setVisible(False)
        self.display_time_table.horizontalHeader().setHighlightSections(False)
        self.display_time_table.verticalHeader().setVisible(False)
        self.display_time_table.verticalHeader().setHighlightSections(False)
        self.label_22 = QtWidgets.QLabel(self.visuals)
        self.label_22.setGeometry(QtCore.QRect(310, 130, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.visuals)
        self.label_23.setGeometry(QtCore.QRect(310, 190, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.display_mode_table = QtWidgets.QTableWidget(self.visuals)
        self.display_mode_table.setGeometry(QtCore.QRect(270, 90, 101, 31))
        self.display_mode_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.display_mode_table.setObjectName("display_mode_table")
        self.display_mode_table.setColumnCount(1)
        self.display_mode_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.display_mode_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.display_mode_table.setHorizontalHeaderItem(0, item)
        self.display_mode_table.horizontalHeader().setVisible(False)
        self.display_mode_table.horizontalHeader().setHighlightSections(False)
        self.display_mode_table.verticalHeader().setVisible(False)
        self.display_mode_table.verticalHeader().setHighlightSections(False)
        self.progressBar = QtWidgets.QProgressBar(self.visuals)
        self.progressBar.setGeometry(QtCore.QRect(260, 290, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.stackedWidget.addWidget(self.visuals)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.OK_btn = QtWidgets.QPushButton(self.page)
        self.OK_btn.setEnabled(False)
        self.OK_btn.setGeometry(QtCore.QRect(270, 271, 113, 101))
        self.OK_btn.setObjectName("OK_btn")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(200, 110, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.serial_port = QtWidgets.QComboBox(self.page)
        self.serial_port.setGeometry(QtCore.QRect(260, 200, 131, 26))
        self.serial_port.setObjectName("serial_port")
        self.scan_btn = QtWidgets.QPushButton(self.page)
        self.scan_btn.setGeometry(QtCore.QRect(190, 190, 61, 61))
        self.scan_btn.setObjectName("scan_btn")
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 628, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Configuration"))
        self.mode_btn.setText(_translate("MainWindow", "Mode"))
        self.syringe_btn.setText(_translate("MainWindow", "Syringe"))
        self.rate_btn.setText(_translate("MainWindow", "Rate"))
        self.target_btn.setText(_translate("MainWindow", "Target"))
        self.empty_btn.setText(_translate("MainWindow", "Fast Empty"))
        self.fill_btn.setText(_translate("MainWindow", "Fast Fill"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.checkBox.setText(_translate("MainWindow", "All Correct"))
        item = self.mode_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.mode_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.syringe_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.syringe_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.rate_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.rate_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.target_table_vol.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.target_table_vol.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.target_table_time.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.target_table_time.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_21.setText(_translate("MainWindow", "="))
        self.label_2.setText(_translate("MainWindow", "Mode Select"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Pumping"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Filling"))
        self.done1_btn.setText(_translate("MainWindow", "Done"))
        self.label_3.setText(_translate("MainWindow", "Syringe Select"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Custom"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Hamilton Gastight (5ml)"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Hamilton Gastight (10ml)"))
        self.done2_btn.setText(_translate("MainWindow", "Done"))
        self.label_7.setText(_translate("MainWindow", "Custom Dimensions:"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Volume (ml)</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Inner Diameter (mm)</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Flow Rate"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "μl/sec"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "μl/min"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "ml/sec"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "ml/min"))
        self.label_9.setText(_translate("MainWindow", "Unit vol. per unit time"))
        self.label_10.setText(_translate("MainWindow", "Max Rate:"))
        self.label_11.setText(_translate("MainWindow", "Min Rate:"))
        item = self.maxrate_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.maxrate_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_12.setText(_translate("MainWindow", "Set Rate:"))
        self.done3_btn.setText(_translate("MainWindow", "Done"))
        item = self.minrate_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.minrate_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.stepres_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.stepres_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_20.setText(_translate("MainWindow", "Step Resolution:"))
        item = self.units_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.units_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_5.setText(_translate("MainWindow", "Target Select"))
        self.radioButton.setText(_translate("MainWindow", "Volume"))
        self.radioButton_2.setText(_translate("MainWindow", "Time"))
        self.label_13.setText(_translate("MainWindow", "Secs"))
        self.label_14.setText(_translate("MainWindow", "μl"))
        self.label_15.setText(_translate("MainWindow", "Max volume:"))
        self.label_16.setText(_translate("MainWindow", "Max time:"))
        self.done4_btn.setText(_translate("MainWindow", "Done"))
        self.label_6.setText(_translate("MainWindow", "Progress"))
        self.stop_btn.setText(_translate("MainWindow", "STOP"))
        item = self.display_rate_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.display_rate_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.display_time_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.display_time_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_22.setText(_translate("MainWindow", "at"))
        self.label_23.setText(_translate("MainWindow", "for"))
        item = self.display_mode_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.display_mode_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        self.OK_btn.setText(_translate("MainWindow", "OK"))
        self.label_18.setText(_translate("MainWindow", "Select serial port:"))
        self.label_19.setText(_translate("MainWindow", "Configuration"))
        self.scan_btn.setText(_translate("MainWindow", "Scan"))

